language: node_js
node_js:
  - '8'

branches:
  only:
    - develop
    - master

# cache dependencies to speed build time
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Travis-CI-supports-yarn
cache: yarn

before_install:
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n" >> .npmrc

install:
  - npm install --global lerna
  - lerna bootstrap
  - lerna run prepublishOnly

script:
  - lerna --since=develop run test

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && lerna publish
