language: node_js
node_js:
  - '6'

branches:
  only:
    - develop
    - master

# cache dependencies to speed build time
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Travis-CI-supports-yarn
cache: yarn

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm publish
