language: node_js
node_js:
  - '8'

branches:
  only:
    - develop
    - master

# cache dependencies to speed build time
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Travis-CI-supports-yarn
cache: yarn

before_install:
  - yarn travis:preinstall

before_script:
  - yarn travis:postinstall

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && lerna --bail=false exec -- 'can-npm-publish && npm publish'
